# Generated by Django 5.1.8 on 2025-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservedMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='kraj',
            field=models.CharField(default='Polska', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='zdjecie',
            field=models.CharField(default='', max_length=255),
        ),
    ]
