# Generated by Django 5.1.8 on 2025-04-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservedMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokoj',
            old_name='licza_pokoi',
            new_name='liczba_pokoi',
        ),
    ]
