# Generated by Django 5.1.8 on 2025-04-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservedMe', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilu_osobowy', models.IntegerField()),
                ('numer_pokoju', models.IntegerField()),
                ('cena_za_noc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokoje', to='ReservedMe.hotel')),
            ],
        ),
    ]
