# Generated by Django 5.1.8 on 2025-04-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservedMe', '0003_pokoj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('calkowita_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_wykonania', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='ReservedMe.hotel')),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='ReservedMe.pokoj')),
            ],
        ),
    ]
