# Generated by Django 5.2 on 2025-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservedMe', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='licza_pokoi',
            field=models.IntegerField(default=1),
        ),
    ]
